<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        // \DB::table('countries')->truncate();

        $countries = [
            ['name_en' => 'Afghanistan', 'name_ar' => 'أفغانستان'],
            ['name_en' => 'Åland Islands', 'name_ar' => 'جزر آلاند'],
            ['name_en' => 'Albania', 'name_ar' => 'ألبانيا'],
            ['name_en' => 'Algeria', 'name_ar' => 'الجزائر'],
            ['name_en' => 'American Samoa', 'name_ar' => 'ساموا الأمريكية'],
            ['name_en' => 'Andorra', 'name_ar' => 'أندورا'],
            ['name_en' => 'Angola', 'name_ar' => 'أنغولا'],
            ['name_en' => 'Anguilla', 'name_ar' => 'أنغيلا'],
            ['name_en' => 'Antarctica', 'name_ar' => 'أنتاركتيكا'],
            ['name_en' => 'Antigua and Barbuda', 'name_ar' => 'أنتيغوا وبربودا'],
            ['name_en' => 'Argentina', 'name_ar' => 'الأرجنتين'],
            ['name_en' => 'Armenia', 'name_ar' => 'أرمينيا'],
            ['name_en' => 'Aruba', 'name_ar' => 'أروبا'],
            ['name_en' => 'Australia', 'name_ar' => 'أستراليا'],
            ['name_en' => 'Austria', 'name_ar' => 'النمسا'],
            ['name_en' => 'Azerbaijan', 'name_ar' => 'أذربيجان'],
            ['name_en' => 'Bahamas', 'name_ar' => 'جزر البهاما'],
            ['name_en' => 'Bahrain', 'name_ar' => 'البحرين'],
            ['name_en' => 'Bangladesh', 'name_ar' => 'بنغلاديش'],
            ['name_en' => 'Barbados', 'name_ar' => 'بربادوس'],
            ['name_en' => 'Belarus', 'name_ar' => 'بيلاروسيا'],
            ['name_en' => 'Belgium', 'name_ar' => 'بلجيكا'],
            ['name_en' => 'Belize', 'name_ar' => 'بليز'],
            ['name_en' => 'Benin', 'name_ar' => 'بنين'],
            ['name_en' => 'Bermuda', 'name_ar' => 'برمودا'],
            ['name_en' => 'Bhutan', 'name_ar' => 'بوتان'],
            ['name_en' => 'Bolivia', 'name_ar' => 'بوليفيا'],
            ['name_en' => 'Bonaire, Sint Eustatius and Saba', 'name_ar' => 'بونير وسانت يوستاتيوس وسابا'],
            ['name_en' => 'Bosnia and Herzegovina', 'name_ar' => 'البوسنة والهرسك'],
            ['name_en' => 'Botswana', 'name_ar' => 'بوتسوانا'],
            ['name_en' => 'Bouvet Island', 'name_ar' => 'جزيرة بوفيت'],
            ['name_en' => 'Brazil', 'name_ar' => 'البرازيل'],
            ['name_en' => 'British Indian Ocean Territory', 'name_ar' => 'إقليم المحيط البريطاني الهندي'],
            ['name_en' => 'Brunei', 'name_ar' => 'بروناي'],
            ['name_en' => 'Bulgaria', 'name_ar' => 'بلغاريا'],
            ['name_en' => 'Burkina Faso', 'name_ar' => 'بوركينا فاسو'],
            ['name_en' => 'Burundi', 'name_ar' => 'بوروندي'],
            ['name_en' => 'Cambodia', 'name_ar' => 'كمبوديا'],
            ['name_en' => 'Cameroon', 'name_ar' => 'الكاميرون'],
            ['name_en' => 'Canada', 'name_ar' => 'كندا'],
            ['name_en' => 'Cape Verde', 'name_ar' => 'الرأس الأخضر'],
            ['name_en' => 'Cayman Islands', 'name_ar' => 'جزر كايمان'],
            ['name_en' => 'Central African Republic', 'name_ar' => 'جمهورية افريقيا الوسطى'],
            ['name_en' => 'Chad', 'name_ar' => 'تشاد'],
            ['name_en' => 'Chile', 'name_ar' => 'تشيلي'],
            ['name_en' => 'China', 'name_ar' => 'الصين'],
            ['name_en' => 'Christmas Island', 'name_ar' => 'جزيرة الكريسماس'],
            ['name_en' => 'Cocos (Keeling) Islands', 'name_ar' => 'جزر كوكوس (كيلينغ)'],
            ['name_en' => 'Colombia', 'name_ar' => 'كولومبيا'],
            ['name_en' => 'Comoros', 'name_ar' => 'جزر القمر'],
            ['name_en' => 'Congo', 'name_ar' => 'الكونغو'],
            ['name_en' => 'Congo, the Democratic Republic of the', 'name_ar' => 'جمهورية الكونغو الديمقراطية'],
            ['name_en' => 'Cook Islands', 'name_ar' => 'جزر كوك'],
            ['name_en' => 'Costa Rica', 'name_ar' => 'كوستا ريكا'],
            ['name_en' => 'Côte d\'Ivoire', 'name_ar' => 'كوت ديفوار'],
            ['name_en' => 'Croatia', 'name_ar' => 'كرواتيا'],
            ['name_en' => 'Cuba', 'name_ar' => 'كوبا'],
            ['name_en' => 'Curaçao', 'name_ar' => 'كوراساو'],
            ['name_en' => 'Cyprus', 'name_ar' => 'قبرص'],
            ['name_en' => 'Czech Republic', 'name_ar' => 'الجمهورية التشيكية'],
            ['name_en' => 'Denmark', 'name_ar' => 'الدنمارك'],
            ['name_en' => 'Djibouti', 'name_ar' => 'جيبوتي'],
            ['name_en' => 'Dominica', 'name_ar' => 'دومينيكا'],
            ['name_en' => 'Dominican Republic', 'name_ar' => 'جمهورية الدومينيكان'],
            ['name_en' => 'Ecuador', 'name_ar' => 'الاكوادور'],
            ['name_en' => 'Egypt', 'name_ar' => 'مصر'],
            ['name_en' => 'El Salvador', 'name_ar' => 'السلفادور'],
            ['name_en' => 'Equatorial Guinea', 'name_ar' => 'غينيا الإستوائية'],
            ['name_en' => 'Eritrea', 'name_ar' => 'إريتريا'],
            ['name_en' => 'Estonia', 'name_ar' => 'إستونيا'],
            ['name_en' => 'Ethiopia', 'name_ar' => 'أثيوبيا'],
            ['name_en' => 'Falkland Islands (Malvinas)', 'name_ar' => 'جزر فوكلاند (مالفيناس)'],
            ['name_en' => 'Faroe Islands', 'name_ar' => 'جزر فاروس'],
            ['name_en' => 'Fiji', 'name_ar' => 'فيجي'],
            ['name_en' => 'Finland', 'name_ar' => 'فنلندا'],
            ['name_en' => 'France', 'name_ar' => 'فرنسا'],
            ['name_en' => 'French Guiana', 'name_ar' => 'غيانا الفرنسية'],
            ['name_en' => 'French Polynesia', 'name_ar' => 'بولينيزيا الفرنسية'],
            ['name_en' => 'French Southern Territories', 'name_ar' => 'المناطق الجنوبية لفرنسا'],
            ['name_en' => 'Gabon', 'name_ar' => 'الجابون'],
            ['name_en' => 'Gambia', 'name_ar' => 'غامبيا'],
            ['name_en' => 'Georgia', 'name_ar' => 'جورجيا'],
            ['name_en' => 'Germany', 'name_ar' => 'ألمانيا'],
            ['name_en' => 'Ghana', 'name_ar' => 'غانا'],
            ['name_en' => 'Gibraltar', 'name_ar' => 'جبل طارق'],
            ['name_en' => 'Greece', 'name_ar' => 'اليونان'],
            ['name_en' => 'Greenland', 'name_ar' => 'الأرض الخضراء'],
            ['name_en' => 'Grenada', 'name_ar' => 'غرينادا'],
            ['name_en' => 'Guadeloupe', 'name_ar' => 'جوادلوب'],
            ['name_en' => 'Guam', 'name_ar' => 'غوام'],
            ['name_en' => 'Guatemala', 'name_ar' => 'غواتيمالا'],
            ['name_en' => 'Guernsey', 'name_ar' => 'غيرنسي'],
            ['name_en' => 'Guinea', 'name_ar' => 'غينيا'],
            ['name_en' => 'Guinea-Bissau', 'name_ar' => 'غينيا بيساو'],
            ['name_en' => 'Guyana', 'name_ar' => 'غيانا'],
            ['name_en' => 'Haiti', 'name_ar' => 'هايتي'],
            ['name_en' => 'Heard Island and McDonald Mcdonald Islands', 'name_ar' => 'جزيرة هيرد وجزر ماكدونالد ماكدونالد'],
            ['name_en' => 'Vatican City State', 'name_ar' => 'دولة مدينة الفاتيكان'],
            ['name_en' => 'Honduras', 'name_ar' => 'هندوراس'],
            ['name_en' => 'Hong Kong', 'name_ar' => 'هونج كونج'],
            ['name_en' => 'Hungary', 'name_ar' => 'هنغاريا'],
            ['name_en' => 'Iceland', 'name_ar' => 'أيسلندا'],
            ['name_en' => 'India', 'name_ar' => 'الهند'],
            ['name_en' => 'Indonesia', 'name_ar' => 'إندونيسيا'],
            ['name_en' => 'Iran', 'name_ar' => 'إيران'],
            ['name_en' => 'Iraq', 'name_ar' => 'العراق'],
            ['name_en' => 'Ireland', 'name_ar' => 'أيرلندا'],
            ['name_en' => 'Isle of Man', 'name_ar' => 'جزيرة آيل أوف مان'],
            ['name_en' => 'Italy', 'name_ar' => 'إيطاليا'],
            ['name_en' => 'Jamaica', 'name_ar' => 'جامايكا'],
            ['name_en' => 'Japan', 'name_ar' => 'اليابان'],
            ['name_en' => 'Jersey', 'name_ar' => 'جيرسي'],
            ['name_en' => 'Jordan', 'name_ar' => 'الأردن'],
            ['name_en' => 'Kazakhstan', 'name_ar' => 'كازاخستان'],
            ['name_en' => 'Kenya', 'name_ar' => 'كينيا'],
            ['name_en' => 'Kiribati', 'name_ar' => 'كيريباتي'],
            ['name_en' => 'Korea, Democratic People\'s Republic of', 'name_ar' => 'كوريا، الجمهورية الشعبية الديمقراطية'],
            ['name_en' => 'Korea, Republic of', 'name_ar' => 'جمهورية كوريا'],
            ['name_en' => 'Kuwait', 'name_ar' => 'الكويت'],
            ['name_en' => 'Kyrgyzstan', 'name_ar' => 'قيرغيزستان'],
            ['name_en' => 'Lao People\'s Democratic Republic', 'name_ar' => 'جمهورية لاو الديمقراطية الشعبية'],
            ['name_en' => 'Latvia', 'name_ar' => 'لاتفيا'],
            ['name_en' => 'Lebanon', 'name_ar' => 'لبنان'],
            ['name_en' => 'Lesotho', 'name_ar' => 'ليسوتو'],
            ['name_en' => 'Liberia', 'name_ar' => 'ليبيريا'],
            ['name_en' => 'Libya', 'name_ar' => 'ليبيا'],
            ['name_en' => 'Liechtenstein', 'name_ar' => 'ليختنشتاين'],
            ['name_en' => 'Lithuania', 'name_ar' => 'ليتوانيا'],
            ['name_en' => 'Luxembourg', 'name_ar' => 'لوكسمبورغ'],
            ['name_en' => 'Macao', 'name_ar' => 'ماكاو'],
            ['name_en' => 'Macedonia', 'name_ar' => 'مقدونيا'],
            ['name_en' => 'Madagascar', 'name_ar' => 'مدغشقر'],
            ['name_en' => 'Malawi', 'name_ar' => 'ملاوي'],
            ['name_en' => 'Malaysia', 'name_ar' => 'ماليزيا'],
            ['name_en' => 'Maldives', 'name_ar' => 'جزر المالديف'],
            ['name_en' => 'Mali', 'name_ar' => 'مالي'],
            ['name_en' => 'Malta', 'name_ar' => 'مالطا'],
            ['name_en' => 'Marshall Islands', 'name_ar' => 'جزر مارشال'],
            ['name_en' => 'Martinique', 'name_ar' => 'مارتينيك'],
            ['name_en' => 'Mauritania', 'name_ar' => 'موريتانيا'],
            ['name_en' => 'Mauritius', 'name_ar' => 'موريشيوس'],
            ['name_en' => 'Mayotte', 'name_ar' => 'مايوت'],
            ['name_en' => 'Mexico', 'name_ar' => 'المكسيك'],
            ['name_en' => 'Micronesia, Federated States of', 'name_ar' => 'ولايات ميكرونيزيا الموحدة'],
            ['name_en' => 'Moldova, Republic of', 'name_ar' => 'جمهورية مولدوفا'],
            ['name_en' => 'Monaco', 'name_ar' => 'موناكو'],
            ['name_en' => 'Mongolia', 'name_ar' => 'منغوليا'],
            ['name_en' => 'Montenegro', 'name_ar' => 'الجبل الأسود'],
            ['name_en' => 'Montserrat', 'name_ar' => 'مونتسيرات'],
            ['name_en' => 'Morocco', 'name_ar' => 'المغرب'],
            ['name_en' => 'Mozambique', 'name_ar' => 'موزمبيق'],
            ['name_en' => 'Myanmar', 'name_ar' => 'ميانمار'],
            ['name_en' => 'Namibia', 'name_ar' => 'ناميبيا'],
            ['name_en' => 'Nauru', 'name_ar' => 'ناورو'],
            ['name_en' => 'Nepal', 'name_ar' => 'نيبال'],
            ['name_en' => 'Netherlands', 'name_ar' => 'هولندا'],
            ['name_en' => 'New Caledonia', 'name_ar' => 'كاليدونيا الجديدة'],
            ['name_en' => 'New Zealand', 'name_ar' => 'نيوزيلاندا'],
            ['name_en' => 'Nicaragua', 'name_ar' => 'نيكاراغوا'],
            ['name_en' => 'Niger', 'name_ar' => 'النيجر'],
            ['name_en' => 'Nigeria', 'name_ar' => 'نيجيريا'],
            ['name_en' => 'Niue', 'name_ar' => 'نيوي'],
            ['name_en' => 'Norfolk Island', 'name_ar' => 'جزيرة نورفولك'],
            ['name_en' => 'Northern Mariana Islands', 'name_ar' => 'جزر مريانا الشمالية'],
            ['name_en' => 'Norway', 'name_ar' => 'النرويج'],
            ['name_en' => 'Oman', 'name_ar' => 'سلطنة عمان'],
            ['name_en' => 'Pakistan', 'name_ar' => 'باكستان'],
            ['name_en' => 'Palau', 'name_ar' => 'بالاو'],
            ['name_en' => 'Palestine', 'name_ar' => 'فلسطين'],
            ['name_en' => 'Panama', 'name_ar' => 'بنما'],
            ['name_en' => 'Papua New Guinea', 'name_ar' => 'بابوا غينيا الجديدة'],
            ['name_en' => 'Paraguay', 'name_ar' => 'باراغواي'],
            ['name_en' => 'Peru', 'name_ar' => 'بيرو'],
            ['name_en' => 'Philippines', 'name_ar' => 'الفلبين'],
            ['name_en' => 'Pitcairn', 'name_ar' => 'بيتكيرن'],
            ['name_en' => 'Poland', 'name_ar' => 'بولندا'],
            ['name_en' => 'Portugal', 'name_ar' => 'البرتغال'],
            ['name_en' => 'Puerto Rico', 'name_ar' => 'بورتوريكو'],
            ['name_en' => 'Qatar', 'name_ar' => 'قطر'],
            ['name_en' => 'Romania', 'name_ar' => 'رومانيا'],
            ['name_en' => 'Russia', 'name_ar' => 'روسيا'],
            ['name_en' => 'Rwanda', 'name_ar' => 'رواندا'],
            ['name_en' => 'Saint Barthélemy', 'name_ar' => 'سانت بارتيليمي'],
            ['name_en' => 'Saint Martin (French part)', 'name_ar' => 'سانت مارتن (الجزء الفرنسي)'],
            ['name_en' => 'Saint Pierre and Miquelon', 'name_ar' => 'PM'],
            ['name_en' => 'Saint Vincent and the Grenadines', 'name_ar' => 'سانت بيير وميكلون'],
            ['name_en' => 'Samoa', 'name_ar' => 'ساموا'],
            ['name_en' => 'San Marino', 'name_ar' => 'سان مارينو'],
            ['name_en' => 'Saudi Arabia', 'name_ar' => 'المملكة العربية السعودية'],
            ['name_en' => 'Senegal', 'name_ar' => 'السنغال'],
            ['name_en' => 'Serbia', 'name_ar' => 'صربيا'],
            ['name_en' => 'Seychelles', 'name_ar' => 'سيشيل'],
            ['name_en' => 'Sierra Leone', 'name_ar' => 'سيرا ليون'],
            ['name_en' => 'Singapore', 'name_ar' => 'سنغافورة'],
            ['name_en' => 'Sint Maarten (Dutch part)', 'name_ar' => 'سينت مارتن (الجزء الهولندي)'],
            ['name_en' => 'Slovakia', 'name_ar' => 'سلوفاكيا'],
            ['name_en' => 'Slovenia', 'name_ar' => 'سلوفينيا'],
            ['name_en' => 'Solomon Islands', 'name_ar' => 'جزر سليمان'],
            ['name_en' => 'Somalia', 'name_ar' => 'الصومال'],
            ['name_en' => 'South Africa', 'name_ar' => 'جنوب أفريقيا'],
            ['name_en' => 'South Georgia and the South Sandwich Islands', 'name_ar' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية'],
            ['name_en' => 'South Sudan', 'name_ar' => 'جنوب السودان'],
            ['name_en' => 'Spain', 'name_ar' => 'إسبانيا'],
            ['name_en' => 'Sri Lanka', 'name_ar' => 'سيريلانكا'],
            ['name_en' => 'Sudan', 'name_ar' => 'السودان'],
            ['name_en' => 'Suriname', 'name_ar' => 'سورينام'],
            ['name_en' => 'Svalbard and Jan Mayen', 'name_ar' => 'سفالبارد وجان ماين'],
            ['name_en' => 'Swaziland', 'name_ar' => 'سوازيلاند'],
            ['name_en' => 'Sweden', 'name_ar' => 'السويد'],
            ['name_en' => 'Switzerland', 'name_ar' => 'سويسرا'],
            ['name_en' => 'Syrian Arab Republic', 'name_ar' => 'سوريا'],
            ['name_en' => 'Taiwan', 'name_ar' => 'تايوان'],
            ['name_en' => 'Tajikistan', 'name_ar' => 'طاجيكستان'],
            ['name_en' => 'Tanzania, United Republic of', 'name_ar' => 'جمهورية تنزانيا المتحدة'],
            ['name_en' => 'Thailand', 'name_ar' => 'تايلاند'],
            ['name_en' => 'Timor-Leste', 'name_ar' => 'Timor-Leste'],
            ['name_en' => 'Togo', 'name_ar' => 'توجو'],
            ['name_en' => 'Tokelau', 'name_ar' => 'توكيلاو'],
            ['name_en' => 'Tonga', 'name_ar' => 'تونغا'],
            ['name_en' => 'Trinidad and Tobago', 'name_ar' => 'ترينداد وتوباغو'],
            ['name_en' => 'Tunisia', 'name_ar' => 'تونس'],
            ['name_en' => 'Turkey', 'name_ar' => 'تركيا'],
            ['name_en' => 'Turkmenistan', 'name_ar' => 'تركمانستان'],
            ['name_en' => 'Turks and Caicos Islands', 'name_ar' => 'جزر تركس وكايكوس'],
            ['name_en' => 'Tuvalu', 'name_ar' => 'توفالو'],
            ['name_en' => 'Uganda', 'name_ar' => 'أوغندا'],
            ['name_en' => 'Ukraine', 'name_ar' => 'أوكرانيا'],
            ['name_en' => 'United Arab Emirates', 'name_ar' => 'الإمارات العربية المتحدة'],
            ['name_en' => 'United Kingdom', 'name_ar' => 'المملكة المتحدة'],
            ['name_en' => 'United States', 'name_ar' => 'الولايات المتحدة'],
            ['name_en' => 'United States Minor Outlying Islands', 'name_ar' => 'جزر الولايات المتحدة البعيدة الصغرى'],
            ['name_en' => 'Uruguay', 'name_ar' => 'أوروغواي'],
            ['name_en' => 'Uzbekistan', 'name_ar' => 'أوزبكستان'],
            ['name_en' => 'Vanuatu', 'name_ar' => 'فانواتو'],
            ['name_en' => 'Venezuela, Bolivarian Republic of', 'name_ar' => 'جمهورية فنزويلا البوليفارية'],
            ['name_en' => 'Viet Nam', 'name_ar' => 'فييت نام'],
            ['name_en' => 'Virgin Islands, British', 'name_ar' => 'جزر فيرجن البريطانية'],
            ['name_en' => 'Virgin Islands, U.S.', 'name_ar' => 'جزر فيرجن الأمريكية'],
            ['name_en' => 'Wallis and Futuna', 'name_ar' => 'واليس وفوتونا'],
            ['name_en' => 'Western Sahara', 'name_ar' => 'الصحراء الغربية'],
            ['name_en' => 'Yemen', 'name_ar' => 'اليمن'],
            ['name_en' => 'Zambia', 'name_ar' => 'زامبيا'],
            ['name_en' => 'Zimbabwe', 'name_ar' => 'زيمبابوي'],
        ];



        DB::table('countries')->insert($countries);
    }
}
